#pragma once

#define WOW_OPTIMIZE_VERSION_MAJOR  2
#define WOW_OPTIMIZE_VERSION_MINOR  0
#define WOW_OPTIMIZE_VERSION_PATCH  9
#define WOW_OPTIMIZE_VERSION_BUILD  0

#define WOW_OPTIMIZE_VERSION_STR    "2.0.9"
#define WOW_OPTIMIZE_AUTHOR         "SUPREMATIST"