#pragma once

#define WOW_OPTIMIZE_VERSION_MAJOR  2
#define WOW_OPTIMIZE_VERSION_MINOR  3
#define WOW_OPTIMIZE_VERSION_PATCH  0
#define WOW_OPTIMIZE_VERSION_BUILD  0

#define WOW_OPTIMIZE_VERSION_STR    "2.3.0"
#define WOW_OPTIMIZE_AUTHOR         "SUPREMATIST"